#!/bin/bash
# Quick manual test to check Mandala Chain via Polkadot.js Apps

echo "🔍 Testing Mandala Chain Contract Support"
echo ""
echo "═══════════════════════════════════════════════════"
echo "MANUAL CHECK REQUIRED"
echo "═══════════════════════════════════════════════════"
echo ""
echo "1️⃣  Open Polkadot.js Apps connected to Mandala:"
echo "   https://polkadot.js.org/apps/?rpc=wss://rpc2.paseo.mandalachain.io#/explorer"
echo ""
echo "2️⃣  Check if Contracts pallet exists:"
echo "   - Go to: Developer → Chain State"
echo "   - Look for 'contracts' in the pallet dropdown"
echo "   - If 'contracts' is available → ✅ Supports ink! contracts"
echo "   - If 'contracts' is NOT there → ❌ Does NOT support ink! contracts"
echo ""
echo "3️⃣  Test your contract address (if contracts pallet exists):"
echo "   - Go to: Developer → Contracts"
echo "   - Look for: 14R7BucJsVzszaZy844PTtJQPp4j9mSELjdvEktf7YZ2sT5N"
echo "   - If listed → ✅ Contract exists"
echo "   - If not listed, try 'Add existing contract' with this address"
echo ""
echo "4️⃣  Query the contract (if it exists):"
echo "   - Click on your contract"
echo "   - Try query: 'getCampaignCount'"
echo "   - Should return: 0 or a number"
echo ""
echo "═══════════════════════════════════════════════════"
echo "ALTERNATIVE RPC ENDPOINTS TO TRY:"
echo "═══════════════════════════════════════════════════"
echo ""
echo "If Mandala doesn't support contracts, try these instead:"
echo ""
echo "📍 Rococo Contracts (guaranteed to work):"
echo "   https://polkadot.js.org/apps/?rpc=wss://rococo-contracts-rpc.polkadot.io#/contracts"
echo ""
echo "📍 Paseo Contracts (if available):"
echo "   https://polkadot.js.org/apps/?rpc=wss://paseo-contracts-rpc.polkadot.io#/contracts"
echo ""
echo "📍 Alternative Mandala RPC:"
echo "   https://polkadot.js.org/apps/?rpc=wss://rpc.paseo.mandalachain.io#/explorer"
echo ""
echo "═══════════════════════════════════════════════════"
echo "CURRENT STATUS:"
echo "═══════════════════════════════════════════════════"
echo "✅ Contract address set in .env.local"
echo "✅ Contract address: 14R7BucJsVzszaZy844PTtJQPp4j9mSELjdvEktf7YZ2sT5N"
echo "✅ RPC endpoint: wss://rpc2.paseo.mandalachain.io"
echo ""
echo "⏳ Waiting for manual verification..."
echo ""
