#!/bin/bash

# Contract Verification Test Script
# Run this to test your contract deployment on Paseo testnet

echo "╔════════════════════════════════════════════════════════════╗"
echo "║      DotNation Contract Verification Test Suite           ║"
echo "║      Paseo Testnet via Mandala Chain RPC                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

CONTRACT_ADDRESS="14R7BucJsVzszaZy844PTtJQPp4j9mSELjdvEktf7YZ2sT5N"
RPC_ENDPOINT="wss://rpc2.paseo.mandalachain.io"
CONTRACTS_UI_URL="https://polkadot.js.org/apps/?rpc=${RPC_ENDPOINT}#/contracts"

echo "📋 Contract Information:"
echo "   Address: ${CONTRACT_ADDRESS}"
echo "   Network: Paseo Testnet (Mandala Chain RPC)"
echo "   RPC:     ${RPC_ENDPOINT}"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Manual Verification via Polkadot.js Apps UI"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open Polkadot.js Apps Contracts UI:"
echo "   ${CONTRACTS_UI_URL}"
echo ""
echo "2. Add Existing Contract:"
echo "   • Click 'Add an existing contract'"
echo "   • Contract Address: ${CONTRACT_ADDRESS}"
echo "   • Upload ABI: frontend/src/contracts/donation_platform.json"
echo "   • Click 'Save'"
echo ""
echo "3. Test Query Methods (no gas cost, instant):"
echo "   ┌────────────────────────────────────────────────────────┐"
echo "   │ Method: get_campaign_count                             │"
echo "   │ Expected: 0 (if no campaigns created yet)              │"
echo "   │ Action: Click 'Read' button                            │"
echo "   └────────────────────────────────────────────────────────┘"
echo ""
echo "   ┌────────────────────────────────────────────────────────┐"
echo "   │ Method: get_version                                    │"
echo "   │ Expected: A version number (e.g., 1 or 2)              │"
echo "   │ Action: Click 'Read' button                            │"
echo "   └────────────────────────────────────────────────────────┘"
echo ""
echo "   ┌────────────────────────────────────────────────────────┐"
echo "   │ Method: get_campaigns_paginated                        │"
echo "   │ Parameters: offset=0, limit=10                         │"
echo "   │ Expected: [] (empty array if no campaigns)             │"
echo "   │ Action: Click 'Read' button                            │"
echo "   └────────────────────────────────────────────────────────┘"
echo ""
echo "   ┌────────────────────────────────────────────────────────┐"
echo "   │ Method: get_max_batch_size                             │"
echo "   │ Expected: A number (probably 10 or 100)                │"
echo "   │ Action: Click 'Read' button                            │"
echo "   └────────────────────────────────────────────────────────┘"
echo ""
echo "✅ If all queries return expected results → Contract works!"
echo "❌ If queries fail → Contract may need redeployment"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Test Campaign Creation (requires PAS tokens)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Prerequisites:"
echo "   • Polkadot.js extension installed"
echo "   • Account with at least 1 PAS token"
echo "   • Account connected on Paseo network"
echo ""
echo "1. In Polkadot.js Apps Contracts UI, find your contract"
echo ""
echo "2. Execute: create_campaign"
echo "   Parameters:"
echo "   • title: \"Test Campaign\""
echo "   • description: \"This is a test campaign for verification\""
echo "   • goal: 10000000000000 (10 DOT in plancks)"
echo "   • deadline: $(date -u -v+7d +%s)000 (7 days from now in milliseconds)"
echo "   • beneficiary: <your_wallet_address>"
echo ""
echo "3. Sign and submit transaction"
echo ""
echo "4. Wait for confirmation (6-12 seconds)"
echo ""
echo "5. Query get_campaign_count again:"
echo "   Expected: 1 (after first campaign)"
echo ""
echo "6. Query get_campaign(0) to see your campaign:"
echo "   Expected: Campaign object with your details"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Test Frontend Integration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Terminal 1 - Start Backend:"
echo "   cd gemini-backend"
echo "   npm install"
echo "   npm start"
echo ""
echo "Terminal 2 - Start Frontend:"
echo "   cd frontend"
echo "   npm install"  
echo "   npm run dev"
echo ""
echo "Browser:"
echo "   1. Open http://localhost:5174"
echo "   2. Connect wallet (must be on Paseo network)"
echo "   3. Navigate to 'Create Campaign'"
echo "   4. Fill form and create campaign"
echo "   5. Check if campaign appears in dashboard"
echo ""
echo "Browser Console Checks:"
echo "   ✅ [CampaignContext] contract exists: true"
echo "   ✅ [ApiContext] Connected to: Paseo Testnet"
echo "   ✅ [WalletContext] Connected: <your_address>"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: Verify Results"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Verification Checklist:"
echo "   [ ] Contract queries work in UI"
echo "   [ ] Contract responds to get_campaign_count"
echo "   [ ] Can create campaign via UI"
echo "   [ ] Campaign appears in contract storage"
echo "   [ ] Frontend can connect to contract"
echo "   [ ] Frontend can create campaigns"
echo "   [ ] Campaigns persist across page refreshes"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Quick Links"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Polkadot.js Apps (Contracts):"
echo "   ${CONTRACTS_UI_URL}"
echo ""
echo "Polkadot.js Apps (Accounts):"
echo "   https://polkadot.js.org/apps/?rpc=${RPC_ENDPOINT}#/accounts"
echo ""
echo "Polkadot.js Apps (Explorer):"
echo "   https://polkadot.js.org/apps/?rpc=${RPC_ENDPOINT}#/explorer"
echo ""
echo "Contract Address:"
echo "   ${CONTRACT_ADDRESS}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

read -p "Press Enter to open Polkadot.js Apps in browser (or Ctrl+C to exit)..."

# Open browser (macOS)
if [[ "$OSTYPE" == "darwin"* ]]; then
    open "${CONTRACTS_UI_URL}"
    echo "✅ Browser opened!"
else
    echo "Please manually open: ${CONTRACTS_UI_URL}"
fi

echo ""
echo "📝 Note: Full verification report available in:"
echo "   CONTRACT_VERIFICATION_REPORT.md"
echo ""
